services:
  vituoso:
    image: openlink/virtuoso-opensource-7
    ports:
      - 8890:8890

  graphdb: 
    image: ontotext/graphdb:10.2.2
    ports:
      - 7200:7200

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_PLUGINS='["neosemantics"]' # fix this 
      - NEO4J_AUTH=none

  fuseki:
    image: secoresearch/fuseki
    ports:
      - 3030:3030
    environment:
      - ADMIN_PASSWORD=password
    